# Generated by Django 5.0.1 on 2024-02-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='auther',
            new_name='author',
        ),
    ]
